language: csharp
solution: src/log2html.sln
install:
  - nuget restore src/log2html.sln
  - nuget install NUnit.Console -Version 3.8.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/log2html.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./src/log2html.Test/bin/Release/log2html.Test.dll